#!/bin/bash

# GCP Cloud SQL PostgreSQL 자동 설정 스크립트

set -e

echo "🚀 GCP Cloud SQL PostgreSQL 설정 시작"
echo ""

# 변수 설정
PROJECT_ID=${GCP_PROJECT_ID:-"postgresql-479201"}
REGION="asia-northeast3"
INSTANCE_NAME="shared-postgres-instance"
DB_VERSION="POSTGRES_15"
TIER="db-f1-micro"

echo "📋 설정 정보:"
echo "  - 프로젝트 ID: $PROJECT_ID"
echo "  - 리전: $REGION (서울)"
echo "  - 인스턴스 이름: $INSTANCE_NAME"
echo "  - 데이터베이스 버전: $DB_VERSION"
echo "  - 머신 타입: $TIER"
echo ""

read -p "계속하시겠습니까? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ 취소되었습니다."
    exit 1
fi

# 1. Cloud SQL Admin API 활성화
echo ""
echo "1️⃣  Cloud SQL Admin API 활성화 중..."
gcloud services enable sqladmin.googleapis.com --project=$PROJECT_ID

# 2. 비밀번호 입력
echo ""
echo "2️⃣  PostgreSQL root 비밀번호 설정"
read -sp "비밀번호 입력: " ROOT_PASSWORD
echo
read -sp "비밀번호 확인: " ROOT_PASSWORD_CONFIRM
echo

if [ "$ROOT_PASSWORD" != "$ROOT_PASSWORD_CONFIRM" ]; then
    echo "❌ 비밀번호가 일치하지 않습니다."
    exit 1
fi

# 3. 인스턴스 생성
echo ""
echo "3️⃣  Cloud SQL 인스턴스 생성 중... (5-10분 소요)"
gcloud sql instances create $INSTANCE_NAME \
  --database-version=$DB_VERSION \
  --tier=$TIER \
  --region=$REGION \
  --root-password="$ROOT_PASSWORD" \
  --storage-size=10GB \
  --storage-type=SSD \
  --storage-auto-increase \
  --backup-start-time=03:00 \
  --project=$PROJECT_ID \
  || echo "⚠️  인스턴스가 이미 존재할 수 있습니다."

# 4. 공개 IP 활성화 (개발용)
echo ""
echo "4️⃣  공개 IP 접근 활성화 중..."
gcloud sql instances patch $INSTANCE_NAME \
  --authorized-networks=0.0.0.0/0 \
  --project=$PROJECT_ID

# 5. 인스턴스 정보 확인
echo ""
echo "5️⃣  인스턴스 정보 확인 중..."
INSTANCE_IP=$(gcloud sql instances describe $INSTANCE_NAME \
  --project=$PROJECT_ID \
  --format="get(ipAddresses[0].ipAddress)")

echo ""
echo "✅ Cloud SQL 인스턴스 생성 완료!"
echo ""
echo "📊 연결 정보:"
echo "  - 인스턴스 이름: $INSTANCE_NAME"
echo "  - 공개 IP: $INSTANCE_IP"
echo "  - Connection Name: $PROJECT_ID:$REGION:$INSTANCE_NAME"
echo ""

# 6. Cloud SQL Proxy 다운로드
echo "6️⃣  Cloud SQL Proxy 설정..."
if [ ! -f "/usr/local/bin/cloud-sql-proxy" ]; then
    echo "  Cloud SQL Proxy 다운로드 중..."

    # OS 감지
    OS=$(uname -s | tr '[:upper:]' '[:lower:]')
    ARCH=$(uname -m)

    if [ "$OS" = "darwin" ] && [ "$ARCH" = "arm64" ]; then
        PROXY_URL="https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.8.0/cloud-sql-proxy.darwin.arm64"
    elif [ "$OS" = "darwin" ]; then
        PROXY_URL="https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.8.0/cloud-sql-proxy.darwin.amd64"
    elif [ "$OS" = "linux" ]; then
        PROXY_URL="https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.8.0/cloud-sql-proxy.linux.amd64"
    else
        echo "  ⚠️  자동 다운로드를 지원하지 않는 OS입니다. 수동으로 설치해주세요."
        PROXY_URL=""
    fi

    if [ -n "$PROXY_URL" ]; then
        curl -o /tmp/cloud-sql-proxy $PROXY_URL
        chmod +x /tmp/cloud-sql-proxy
        sudo mv /tmp/cloud-sql-proxy /usr/local/bin/cloud-sql-proxy
        echo "  ✅ Cloud SQL Proxy 설치 완료"
    fi
else
    echo "  ✅ Cloud SQL Proxy 이미 설치됨"
fi

# 7. 환경변수 파일 생성
echo ""
echo "7️⃣  환경변수 파일 업데이트..."

# .env.gcp 파일 생성
cat > .env.gcp << EOF
# GCP Cloud SQL PostgreSQL 설정
# Generated by setup-gcp-postgres.sh

# Cloud SQL 연결 정보
GCP_PROJECT_ID=$PROJECT_ID
GCP_REGION=$REGION
GCP_SQL_INSTANCE=$INSTANCE_NAME
GCP_SQL_CONNECTION_NAME=$PROJECT_ID:$REGION:$INSTANCE_NAME
GCP_SQL_PUBLIC_IP=$INSTANCE_IP

# 로컬 개발 (Cloud SQL Proxy 사용)
DATABASE_URL="postgresql://postgres:$ROOT_PASSWORD@127.0.0.1:5432/dcs_dev"

# 직접 연결 (공개 IP - 보안 주의)
# DATABASE_URL="postgresql://postgres:$ROOT_PASSWORD@$INSTANCE_IP:5432/dcs_dev?sslmode=require"

# GCP 환경 (Unix Socket)
# DATABASE_URL="postgresql://postgres:$ROOT_PASSWORD@/dcs_dev?host=/cloudsql/$PROJECT_ID:$REGION:$INSTANCE_NAME"
EOF

echo "  ✅ .env.gcp 파일 생성 완료"

# 8. 프록시 시작 스크립트 생성
echo ""
echo "8️⃣  프록시 관리 스크립트 생성..."

mkdir -p scripts

cat > scripts/start-gcp-db.sh << 'EOF'
#!/bin/bash

# .env.gcp 파일에서 설정 로드
if [ -f .env.gcp ]; then
    source .env.gcp
else
    echo "❌ .env.gcp 파일이 없습니다."
    exit 1
fi

# Cloud SQL Proxy 실행
echo "🚀 Cloud SQL Proxy 시작 중..."
cloud-sql-proxy --port 5432 $GCP_SQL_CONNECTION_NAME > /dev/null 2>&1 &

# PID 저장
echo $! > .cloud-sql-proxy.pid

sleep 2

if ps -p $(cat .cloud-sql-proxy.pid) > /dev/null; then
    echo "✅ Cloud SQL Proxy 시작됨 (PID: $(cat .cloud-sql-proxy.pid))"
    echo "📡 접속 가능: localhost:5432"
else
    echo "❌ Cloud SQL Proxy 시작 실패"
    rm .cloud-sql-proxy.pid
    exit 1
fi
EOF

cat > scripts/stop-gcp-db.sh << 'EOF'
#!/bin/bash

if [ -f .cloud-sql-proxy.pid ]; then
    PID=$(cat .cloud-sql-proxy.pid)
    if ps -p $PID > /dev/null; then
        kill $PID
        echo "✅ Cloud SQL Proxy 중지됨 (PID: $PID)"
    else
        echo "⚠️  프로세스가 이미 종료됨"
    fi
    rm .cloud-sql-proxy.pid
else
    echo "⚠️  실행 중인 프록시가 없습니다"
fi
EOF

chmod +x scripts/start-gcp-db.sh
chmod +x scripts/stop-gcp-db.sh

echo "  ✅ 스크립트 생성 완료"

# 9. 완료 메시지
echo ""
echo "=========================================="
echo "🎉 GCP Cloud SQL PostgreSQL 설정 완료!"
echo "=========================================="
echo ""
echo "📝 다음 단계:"
echo ""
echo "1. Cloud SQL Proxy 시작:"
echo "   ./scripts/start-gcp-db.sh"
echo ""
echo "2. 데이터베이스 생성 (psql 사용):"
echo "   psql -h 127.0.0.1 -U postgres"
echo "   CREATE DATABASE dcs_dev;"
echo "   CREATE DATABASE dcs_test;"
echo ""
echo "3. .env 파일 업데이트:"
echo "   cp .env.gcp .env"
echo ""
echo "4. Prisma 마이그레이션:"
echo "   npx prisma migrate dev"
echo ""
echo "💡 Tip: 사용하지 않을 때는 인스턴스를 중지하여 비용을 절감하세요:"
echo "   gcloud sql instances patch $INSTANCE_NAME --activation-policy=NEVER"
echo ""
echo "📚 자세한 내용은 docs/GCP_POSTGRESQL_SETUP.md 참고"
echo ""
